app.countries = {
    'AUS': ['Australia', 'AU', '36'],
    'AUT': ['Austria', 'AT', '40'],
    'AZE': ['Azerbaijan', 'AZ', '31'],
    'ALA': ['Aland Islands', 'AX', '248'],
    'ALB': ['Albania', 'AL', '8'],
    'DZA': ['Algeria', 'DZ', '12'],
    'VIR': ['Virgin Islands (USA)', 'VI', '850'],
    'ASM': ['American Samoa', 'AS', '16'],
    'AIA': ['Anguilla', 'AI', '660'],
    'AGO': ['Angola', 'AO', '24'],
    'AND': ['Andorra', 'AD', '20'],
    'ATA': ['Antarctica', 'AQ', '10'],
    'ATG': ['Antigua and Barbuda', 'AG', '28'],
    'ARG': ['Argentina', 'AR', '32'],
    'ARM': ['Armenia', 'AM', '51'],
    'ABW': ['Aruba', 'AW', '533'],
    'AFG': ['Afghanistan', 'AF', '4'],
    'BHS': ['Bahamas', 'BS', '44'],
    'BGD': ['Bangladesh', 'BD', '50'],
    'BRB': ['Barbados', 'BB', '52'],
    'BHR': ['Bahrain', 'BH', '48'],
    'BLZ': ['Belize', 'BZ', '84'],
    'BLR': ['Belarus', 'BY', '112'],
    'BEL': ['Belgium', 'BE', '56'],
    'BEN': ['Benin', 'BJ', '204'],
    'BMU': ['Bermudas', 'BM', '60'],
    'BGR': ['Bulgaria', 'BG', '100'],
    'BOL': ['Bolivia', 'BO', '68'],
    'BES': ['Bonaire, Sint Eustatius and Saba', 'BQ', '535'],
    'BIH': ['Bosnia and Herzegovina', 'BA', '70'],
    'BWA': ['Botswana', 'BW', '72'],
    'BRA': ['Brazil', 'BR', '76'],
    'IOT': ['British Indian Ocean Territory', 'IO', '86'],
    'VGB': ['British Virgin Islands', 'VG', '92'],
    'BRN': ['Brunei', 'BN', '96'],
    'BFA': ['Burkina Faso', 'BF', '854'],
    'BDI': ['Burundi', 'BI', '108'],
    'BTN': ['butane', 'BT', '64'],
    'VUT': ['Vanuatu', 'VU', '548'],
    'VAT': ['Vatican', 'VA', '336'],
    'GBR': ['Great Britain', 'GB', '826'],
    'HUN': ['Hungary', 'HU', '348'],
    'VEN': ['Venezuela', 'VE', '862'],
    'UMI': ['Minor Outlying Islands (United States)', 'UM', '581'],
    'TLS': ['East Timor', 'TL', '626'],
    'VNM': ['Vietnam', 'VN', '704'],
    'GAB': ['Gabon', 'GA', '266'],
    'HTI': ['Haiti', 'HT', '332'],
    'GUY': ['Guyana', 'GY', '328'],
    'GMB': ['Gambia', 'GM', '270'],
    'GHA': ['Ghana', 'GH', '288'],
    'GLP': ['Guadeloupe', 'GP', '312'],
    'GTM': ['Guatemala', 'GT', '320'],
    'GUF': ['Guiana', 'GF', '254'],
    'GIN': ['Guinea', 'GN', '324'],
    'GNB': ['Guinea-Bissau', 'GW', '624'],
    'DEU': ['Germany', 'DE', '276'],
    'GGY': ['Guernsey', 'GG', '831'],
    'GIB': ['Gibraltar', 'GI', '292'],
    'HND': ['Honduras', 'HN', '340'],
    'HKG': ['Hong Kong', 'HK', '344'],
    'GRD': ['Grenada', 'GD', '308'],
    'GRL': ['Greenland', 'GL', '304'],
    'GRC': ['Greece', 'GR', '300'],
    'GEO': ['Georgia', 'GE', '268'],
    'GUM': ['Guam', 'GU', '316'],
    'DNK': ['Denmark', 'DK', '208'],
    'JEY': ['Jersey', 'JE', '832'],
    'DJI': ['Djibouti', 'DJ', '262'],
    'DMA': ['Dominica', 'DM', '212'],
    'DOM': ['Dominican Republic', 'DO', '214'],
    'COD': ['Democratic Republic of the Congo', 'CD', '180'],
    'EGY': ['Egypt', 'EG', '818'],
    'ZMB': ['Zambia', 'ZM', '894'],
    'ESH': ['SADR', 'EH', '732'],
    'ZWE': ['Zimbabwe', 'ZW', '716'],
    'ISR': ['Israel', 'IL', '376'],
    'IND': ['India', 'IN', '356'],
    'IDN': ['Indonesia', 'ID', '360'],
    'JOR': ['Jordan', 'JO', '400'],
    'IRQ': ['Iraq', 'IQ', '368'],
    'IRN': ['Iran', 'IR', '364'],
    'IRL': ['Ireland', 'IE', '372'],
    'ISL': ['Iceland', 'IS', '352'],
    'ESP': ['Spain', 'ES', '724'],
    'ITA': ['Italy', 'IT', '380'],
    'YEM': ['Yemen', 'YE', '887'],
    'CPV': ['Cape Verde', 'CV', '132'],
    'KAZ': ['Kazakhstan', 'KZ', '398'],
    'CYM': ['Cayman Islands', 'KY', '136'],
    'KHM': ['Cambodia', 'KH', '116'],
    'CMR': ['Cameroon', 'CM', '120'],
    'CAN': ['Canada', 'CA', '124'],
    'QAT': ['Qatar', 'QA', '634'],
    'KEN': ['Kenya', 'KE', '404'],
    'CYP': ['Cyprus', 'CY', '196'],
    'KGZ': ['Kyrgyzstan', 'KG', '417'],
    'KIR': ['Kiribati', 'KI', '296'],
    'TWN': ['Republic Of China', 'TW', '158'],
    'PRK': ['North Korea', 'KP', '408'],
    'CHN': ['China', 'CN', '156'],
    'CCK': ['Cocos Islands', 'CC', '166'],
    'COL': ['Colombia', 'CO', '170'],
    'COM': ['Comoros', 'KM', '174'],
    'CRI': ['Costa Rica', 'CR', '188'],
    'CIV': ['Côte d\'Ivoire', 'CI', '384'],
    'CUB': ['Cuba', 'CU', '192'],
    'KWT': ['Kuwait', 'KW', '414'],
    'CUW': ['Curacao', 'CW', '531'],
    'LAO': ['Laos', 'LA', '418'],
    'LVA': ['Latvia', 'LV', '428'],
    'LSO': ['Lesotho', 'LS', '426'],
    'LBR': ['Liberia', 'LR', '430'],
    'LBN': ['Lebanon', 'LB', '422'],
    'LBY': ['Libya', 'LY', '434'],
    'LTU': ['Lithuania', 'LT', '440'],
    'LIE': ['Liechtenstein', 'LI', '438'],
    'LUX': ['Luxembourg', 'LU', '442'],
    'MUS': ['Mauritius', 'MU', '480'],
    'MRT': ['Mauritania', 'MR', '478'],
    'MDG': ['Madagascar', 'MG', '450'],
    'MYT': ['Mayotte', 'YT', '175'],
    'MAC': ['Macau', 'MO', '446'],
    'MKD': ['Macedonia', 'MK', '807'],
    'MWI': ['Malawi', 'MW', '454'],
    'MYS': ['Malaysia', 'MY', '458'],
    'MLI': ['Mali', 'ML', '466'],
    'MDV': ['Maldives', 'MV', '462'],
    'MLT': ['Malta', 'MT', '470'],
    'MAR': ['Morocco', 'MA', '504'],
    'MTQ': ['Martinique', 'MQ', '474'],
    'MHL': ['Marshall Islands', 'MH', '584'],
    'MEX': ['Mexico', 'MX', '484'],
    'FSM': ['Micronesia', 'FM', '583'],
    'MOZ': ['Mozambique', 'MZ', '508'],
    'MDA': ['Moldavia', 'MD', '498'],
    'MCO': ['Monaco', 'MC', '492'],
    'MNG': ['Mongolia', 'MN', '496'],
    'MSR': ['Montserrat', 'MS', '500'],
    'MMR': ['Myanmar', 'MM', '104'],
    'NAM': ['Namibia', 'NA', '516'],
    'NRU': ['Nauru', 'NR', '520'],
    'NPL': ['Nepal', 'NP', '524'],
    'NER': ['Niger', 'NE', '562'],
    'NGA': ['Nigeria', 'NG', '566'],
    'NLD': ['Netherlands', 'NL', '528'],
    'NIC': ['Nicaragua', 'NI', '558'],
    'NIU': ['Niue', 'NU', '570'],
    'NZL': ['New Zealand', 'NZ', '554'],
    'NCL': ['New Caledonia', 'NC', '540'],
    'NOR': ['Norway', 'NO', '578'],
    'ARE': ['UAE', 'AE', '784'],
    'OMN': ['Oman', 'OM', '512'],
    'BVT': ['Bouvet Island', 'BV', '74'],
    'IMN': ['Isle Of Man', 'IM', '833'],
    'COK': ['Cook Islands', 'CK', '184'],
    'NFK': ['Norfolk Island', 'NF', '574'],
    'CXR': ['Christmas Island', 'CX', '162'],
    'PCN': ['Pitcairn Islands', 'PN', '612'],
    'SHN': ['Saint Helena, Ascension and Tristan da Cunha', 'SH', '654'],
    'PAK': ['Pakistan', 'PK', '586'],
    'PLW': ['Palau', 'PW', '585'],
    'PSE': ['The State of Palestine', 'PS', '275'],
    'PAN': ['Panama', 'PA', '591'],
    'PNG': ['Papua New Guinea', 'PG', '598'],
    'PRY': ['Paraguay', 'PY', '600'],
    'PER': ['Peru', 'PE', '604'],
    'POL': ['Poland', 'PL', '616'],
    'PRT': ['Portugal', 'PT', '620'],
    'PRI': ['Puerto-Rico', 'PR', '630'],
    'COG': ['Republic of the Congo', 'CG', '178'],
    'KOR': ['Republic Of Korea', 'KR', '410'],
    'REU': ['Reunion', 'RE', '638'],
    'RUS': ['Russia', 'RU', '643'],
    'RWA': ['Rwanda', 'RW', '646'],
    'ROU': ['Romania', 'RO', '642'],
    'SLV': ['Salvador', 'SV', '222'],
    'WSM': ['Samoa', 'WS', '882'],
    'SMR': ['San Marino', 'SM', '674'],
    'STP': ['Sao Tome and Principe', 'ST', '678'],
    'SAU': ['Saudi Arabia', 'SA', '682'],
    'SWZ': ['Swaziland', 'SZ', '748'],
    'MNP': ['Northern Mariana Islands', 'MP', '580'],
    'SYC': ['Seychelles', 'SC', '690'],
    'BLM': ['Saint Barthelemy', 'BL', '652'],
    'MAF': ['Saint-Martin', 'MF', '663'],
    'SPM': ['Saint Pierre and Miquelon', 'PM', '666'],
    'SEN': ['Senegal', 'SN', '686'],
    'VCT': ['Saint Vincent and the Grenadines', 'VC', '670'],
    'KNA': ['Saint Kitts and Nevis', 'KN', '659'],
    'LCA': ['St. Lucia', 'LC', '662'],
    'SRB': ['Serbia', 'RS', '688'],
    'SGP': ['Singapore', 'SG', '702'],
    'SXM': ['Sint Maarten', 'SX', '534'],
    'SYR': ['Syria', 'SY', '760'],
    'SVK': ['Slovakia', 'SK', '703'],
    'SVN': ['Slovenia', 'SI', '705'],
    'SLB': ['Solomon Islands', 'SB', '90'],
    'SOM': ['Somalia', 'SO', '706'],
    'SDN': ['Sudan', 'SD', '729'],
    'SUN': ['USSR', 'SU', '810'],
    'SUR': ['Surinam', 'SR', '740'],
    'USA': ['United States of America', 'US', '840'],
    'SLE': ['Sierra Leone', 'SL', '694'],
    'TJK': ['Tajikistan', 'TJ', '762'],
    'THA': ['Thailand', 'TH', '764'],
    'TZA': ['Tanzania', 'TZ', '834'],
    'TCA': ['Turks and Caicos Islands', 'TC', '796'],
    'TGO': ['Togo', 'TG', '768'],
    'TKL': ['Tokelau', 'TK', '772'],
    'TON': ['Tonga', 'TO', '776'],
    'TTO': ['TongaTrinidad and Tobago', 'TT', '780'],
    'TUV': ['Tuvalu', 'TV', '798'],
    'TUN': ['Tunisia', 'TN', '788'],
    'TKM': ['Turkmenistan', 'TM', '795'],
    'TUR': ['Turkey', 'TR', '792'],
    'UGA': ['Uganda', 'UG', '800'],
    'UZB': ['Uzbekistan', 'UZ', '860'],
    'UKR': ['Ukraine', 'UA', '804'],
    'WLF': ['Wallis and Futuna Islands', 'WF', '876'],
    'URY': ['Uruguay', 'UY', '858'],
    'FRO': ['Faroe Islands', 'FO', '234'],
    'FJI': ['Fiji', 'FJ', '242'],
    'PHL': ['Philippines', 'PH', '608'],
    'FIN': ['Finland', 'FI', '246'],
    'FLK': ['Falkland Islands', 'FK', '238'],
    'FRA': ['France', 'FR', '250'],
    'PYF': ['French Polynesia', 'PF', '258'],
    'ATF': ['French Southern and Antarctic Lands', 'TF', '260'],
    'HMD': ['Heard and McDonald Islands', 'HM', '334'],
    'HRV': ['Croatia', 'HR', '191'],
    'CAF': ['CAR', 'CF', '140'],
    'TCD': ['Chad', 'TD', '148'],
    'MNE': ['Montenegro', 'ME', '499'],
    'CZE': ['Czech Republic', 'CZ', '203'],
    'CHL': ['Chile', 'CL', '152'],
    'CHE': ['Switzerland', 'CH', '756'],
    'SWE': ['Sweden', 'SE', '752'],
    'SJM': ['Svalbard and Jan Mayen', 'SJ', '744'],
    'LKA': ['Sri Lanka', 'LK', '144'],
    'ECU': ['Ecuador', 'EC', '218'],
    'GNQ': ['Equatorial Guinea', 'GQ', '226'],
    'ERI': ['Eritrea', 'ER', '232'],
    'EST': ['Estonia', 'EE', '233'],
    'ETH': ['Ethiopia', 'ET', '231'],
    'ZAF': ['Republic of South Africa', 'ZA', '710'],
    'SGS': ['South Georgia and South Sandwich Islands', 'GS', '239'],
    'SSD': ['Southern Sudan', 'SS', '728'],
    'JAM': ['Jamaica', 'JM', '388'],
    'JPN': ['Japan', 'JP', '392']
};